### ISSUE TITLE
Using Sympy-bot behind a college proxy

### ISSUE THREAD

**Issue by tardunge** [sympy/sympy-bot-old#104]
Hi..My name is Manoj Babu.I am a 3rd year undergraduate student pursuing my Btech in IIT Kharagpur India.I connect to internet using a proxy address. for example 144.16.192.245:8080..Since the proxy blocks ssh ports i use git bash on windows and git on linux..For pushing into git i need to type these 
$ http_proxy="http://144.16.192.245:8080"
$ export http_proxy
cloning pushing pulling everything is done through http url not git@github.com
I have cloned http://github.com/sympy/sympy-bot.git 
and after typing 
$./sympy-bot review 1152
i get these errors..can anyone fix this??

Manoj@MANOJ-PC /e/gsoc/gamma/sympy-bot (master)
$ ./sympy-bot review 1152
c:/Users/Manoj.sympy\sympy-bot.conf
Enter your GitHub username & password or press ^C to quit. The password
will be kept as a Python variable as long as sympy-bot is running and
https to authenticate with GitHub, otherwise not saved anywhere else:
Username: manoj2378
Password:

> Checking username and password ...
> Traceback (most recent call last):
>   File "./sympy-bot", line 354, in <module>
>     main()
>   File "./sympy-bot", line 132, in main
>     username, password = github_authenticate(options)
>   File "e:\gsoc\gamma\sympy-bot\utils.py", line 302, in github_authenticate
>     password = get_password()
>   File "e:\gsoc\gamma\sympy-bot\utils.py", line 274, in get_password
>     github_check_authentication(username, password)
>   File "e:\gsoc\gamma\sympy-bot\utils.py", line 147, in github_check_authenticat
> ion
>     s = json.load(urllib2.urlopen(request))
>   File "c:\python27\lib\urllib2.py", line 126, in urlopen
>     return _opener.open(url, data, timeout)
>   File "c:\python27\lib\urllib2.py", line 391, in open
>     response = self._open(req, data)
>   File "c:\python27\lib\urllib2.py", line 409, in _open
>     '_open', req)
>   File "c:\python27\lib\urllib2.py", line 369, in _call_chain
>     result = func(*args)
>   File "c:\python27\lib\urllib2.py", line 1181, in https_open
>     return self.do_open(httplib.HTTPSConnection, req)
>   File "c:\python27\lib\urllib2.py", line 1148, in do_open
>     raise URLError(err)
> urllib2.URLError: <urlopen error [Errno 10061] No connection could be made becau
> se the target machine actively refused it>

**Comment by tardunge** [comment]
Please ignore the above console output..The text below is properly copied and pasted

``` pytb
Enter your GitHub username & password or press ^C to quit. The password
will be kept as a Python variable as long as sympy-bot is running and
https to authenticate with GitHub, otherwise not saved anywhere else:
Username: manoj2378
Password:
> Checking username and password ...
Traceback (most recent call last):
  File "./sympy-bot", line 354, in <module>
    main()
  File "./sympy-bot", line 132, in main
    username, password = github_authenticate(options)
  File "e:\gsoc\gamma\sympy-bot\utils.py", line 302, in github_authenticate
    password = get_password()
  File "e:\gsoc\gamma\sympy-bot\utils.py", line 274, in get_password
    github_check_authentication(username, password)
  File "e:\gsoc\gamma\sympy-bot\utils.py", line 147, in github_check_authentication
    s = json.load(urllib2.urlopen(request))
  File "c:\python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "c:\python27\lib\urllib2.py", line 391, in open
    response = self._open(req, data)
  File "c:\python27\lib\urllib2.py", line 409, in _open
    '_open', req)
  File "c:\python27\lib\urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 1181, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "c:\python27\lib\urllib2.py", line 1148, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 10061] No connection could be made because the
the target machine actively refused it>
```

**Comment by MichaelMayorov** [comment]
Why are you using http_proxy if main protocol is https?

try `export https_proxy="http://144.16.192.245:8080"`

**Comment by tardunge** [comment]
Now i get another error probably changing git://github.com/sympy/sympy-bot.git to https might solve it.Will work on it :)

**Comment by MichaelMayorov** [comment]
29.03.2012 05:18, manoj написал:

> Now i get another error probably changing git://github.com/sympy/sympy-bot.git to https might solve it.Will work on it :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sympy/sympy-bot/issues/104#issuecomment-4793728
> You could use protocol switcher with "-p git" option

## 

With best regards,
Mayorov Michael
