### ISSUE TITLE
sympy-bot not posting the review in discussion and raises an error at the end in windows

### ISSUE THREAD

**Issue by sachin004** [sympy/sympy-bot-old#105]
View log at: c:\users\sachin\appdata\local\temp\sympy-bot-tmpwqdddm\out\log

> Uploading test results
> Uploaded report at: http://reviews.sympy.org/report/agZzeW1weTNyDAsSBFRhc2sYn7
> QTDA
> Traceback (most recent call last):
>   File "./sympy-bot", line 354, in <module>
>     main()
>   File "./sympy-bot", line 138, in main
>     proto=proto
>   File "./sympy-bot", line 339, in review
>     xpassed, master_hash, branch_hash, user, config)
>   File "./sympy-bot", line 179, in formulate_review
>     details  = get_platform_version(config.interpreter)
>   File "./sympy-bot", line 241, in get_platform_version
>     size = cmd(call, capture=True)
>   File "c:\Users\sachin\sympy-bot\utils.py", line 49, in cmd
>     raise CmdException("Command '%s' failed with err=%d." % (s, r))
> utils.CmdException: Command 'python -c 'import sys; print(getattr(sys, "maxint",
>  None))'' failed with err=1.

**Comment by asmeurer** [comment]
If you just type `python -c 'import sys; print(getattr(sys, "maxint", None))'` at the terminal, what is the output?

**Comment by sachin004** [comment]
<code>

C:\Windows\System32>python -c 'import sys; print(getattr(sys, "maxint", None))'
  File "<string>", line 1
    'import
          ^
SyntaxError: EOL while scanning string literal
</code>
In the terminal<code>

> > > import sys
> > > print(getattr(sys, "maxint", None))
> > > 2147483647
> > > 
> > > </code>
> > > FYI I am in windows

**Comment by asmeurer** [comment]
Maybe Windows treats quotes differently?  What about `python -c "import sys; print(getattr(sys, 'maxint', None))"` (i.e., reverse `'` and `"`)?

**Comment by flacjacket** [comment]
This should be fixed since #115 was merged.
