### ISSUE TITLE
Make it clearer in the summary when a test has failed

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-bot-old#106]
Right now, the summary for a test failure looks too similar to the summary for tests passing.  They look the same, except for the summary text at the top.  It is too easy to miss a test failure if you aren't careful (like happened at sympy/sympy#1115).  

So we need to make it more prominent when tests failed.  One simple way would be to put the text "there were test failures" in bold, like

**Summary: There were test failures.**

It would be neat if we could use <FONT COLOR="#CCCCCC">colors</FONT>, but GitHub ignores html color tags.  Another idea would be to use some kind of colored symbol.  We could use emoji, like 

**Summary:** :star: All tests passed

and

**Summary:** :red_circle: There were test failures

(do those show up on non-Apple devices?).  See https://github.com/blog/816-emoji and http://www.emoji-cheat-sheet.com/

We could also include some kind of image, like 

**Summary:** <img src="http://upload.wikimedia.org/wikipedia/commons/a/a7/Stop_sign_MUTCD.svg" alt="Stop!" height=25 align=middle></img> There were test failures.

**Comment by smichr** [comment]
> **Summary:** :star: All tests passed
> 
> and
> 
> **Summary:** :red_circle: There were test failures
> 
> :tennis: (green circle) and :x: (red X) look good, too.

or

http://all-free-download.com/free-icon/vista-icon/green_globe_ok_tic_584.html
http://all-free-download.com/free-icon/vista-icon/round_red_x_sign_4229.html

/c

**Comment by toolforger** [comment]
All symbols look good on Linux.
I wouldn't combine red and green circle but make sure that each icon has a noticeably different form.
It's easier to check (at-a-glance checks mostly work via form comparison, color processing in the human brain is slower and less reliable).
Plus if we don't rely on color, colorblind devs will profit, too.

**Comment by smichr** [comment]
On Fri, Apr 6, 2012 at 10:22 PM, Joachim Durchholz <
reply@reply.github.com

> wrote:
> 
> All symbols look good on Linux.
> I wouldn't combine red and green circle but make sure that each icon has a
> noticeably different form.
> It's easier to check (at-a-glance checks mostly work via form comparison,
> color processing in the human brain is slower and less reliable).
> Plus if we don't rely on color, colorblind devs will profit, too.
> 
> How do the red x and green ok check look (the ones I sent in my first
> response)?

**Comment by toolforger** [comment]
They're fine.
I like your set slightly better, but that's probably just personal preference. In general, I'm fine with either proposal. (Resisting the temptation for bikeshedding here ;-) )

I think we should define all situations where we want an icon. Then we'll see how many easily distinguishable icons we need and can choose one icon set. (Aaron's STOP symbol is confusing me here - is that an additional situation? Just a marker for the position in the output stream that we want to alert people to?)

**Comment by asmeurer** [comment]
There's also two other cases, unmergable, and error (when it didn't work for some reason).  My only issue with the green circle is that it looks like a tennis ball (because it indeed is), which could be confusing if you have enough resolution to actually notice it.

**Comment by asmeurer** [comment]
Other possibilities:

:exclamation: `:exclamation:`
:star2: `:star2:`
:anger: `:anger:`
:grey_exclamation: `:grey_exclamation:`
:+1: `:+1:`
:-1: `:-1:`
:ok_hand: `:ok_hand:`
:black_square: `:black_square:`
:white_square: `:white_square:`
:o: `:o:`
:eight_spoked_asterisk: `:eight_spoked_asterisk:`

I'm really fine with any of these (obviously positive ones for tests passed and negative ones for the other cases).

The STOP symbol means "DONT MERGE".  I mainly wanted to demonstrate that you can add any image (to do that, I just wrote `<img src="http://upload.wikimedia.org/wikipedia/commons/a/a7/Stop_sign_MUTCD.svg" alt="Stop!" height=25 align=middle></img>`).

Bikeshedding is fine. Everyone just tell me which ones you like, and then I'll completely ignore it and submit a patch with the ones I like :)

**Comment by asmeurer** [comment]
How about 

:eight_spoked_asterisk: - Tests pass (instead of :tennis: because the tennis ball is confusing and :star: is too similarly colored to text to standout, as are the hand symbols).  It's green, indicating the go ahead, and the symbol somewhat indicates that too.
:red_circle: - Tests failed.  Bright red should be the most alerting.  Different shape than :eight_spoked_asterisk:.
:exclamation: - Could not merge.  It's also red and a universal symbol for, well, exclamation.  Different shape.
:x: - Other failure (I think this comes up when the bot cannot run tests or something).  Again red, and a still different shape.

**Comment by asmeurer** [comment]
Oh, I just noticed :warning: (`:warning:`).  We could use that too.

**Comment by smichr** [comment]
On Sat, Apr 7, 2012 at 9:38 AM, Aaron Meurer
reply@reply.github.com
wrote:

> There's also two other cases, unmergable, and error (when it didn't work for some reason).  My only issue with the green circle is that it looks like a tennis ball (because it indeed is), which could be confusing if you have enough resolution to actually notice it.

Check out the other two options (the X and the check).

**Comment by smichr** [comment]
On Sat, Apr 7, 2012 at 9:59 AM, Aaron Meurer
reply@reply.github.com
wrote:

> How about
> 
> :eight_spoked_asterisk: - Tests pass (instead of :tennis: because the tennis ball is confusing), and :star: is too similarly colored to text to standout.
> :red_circle: - Tests failed.  Bright red should be the most alerting.  Different shape than :eight_spoked_asterisk:.
> :exclamation: - Could not merge.  It's also red and a universal symbol for, well, exclamation.  Different shape.
> :x: - Other failure (I think this comes up when the bot cannot run tests or something).  Again red, and a still different shape.

I like all of these...I didn't realize that the tennis ball really
looked like a tennis ball or else I wouldn't have suggested that one.

**Comment by asmeurer** [comment]
OK, this is now #107.

**Comment by asmeurer** [comment]
Now I'm all high on emoji.  How about putting :2: and :3: somewhere to indicate if the tests were in Python 2 or Python 3?

**Comment by toolforger** [comment]
:lol: just make sure we're not getting too dependent on Github emojis so that they don't become a problem if we ever wish to switch to, say, BitBucket ;-)
