### ISSUE TITLE
Add the ability to clone from local sympy repo

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-bot-old#12]
Add the ability to clone from local sympy repo. Cloning from the internet takes too long.  This should check if the commit HEAD of the pull request is available in the local repo (because it usually will be as a remote).  

And we should be doing shallow clones, since we only care about the HEAD commit, not the entire history (I guess this should actually be a separate issue).

**Comment by certik** [comment]
I think it's already implemented, see the "Tips" section in README and the "--reference" option.

**Comment by asmeurer** [comment]
Well, it doesn't take the remote commit from the local repo.  

And by the way, it doesn't work for relative paths, like `$./sympy-bot review 266 --reference=../sympy/`.  I guess that's expected since it's the argument to `git clone`, but having those work somehow would be nice.

**Comment by certik** [comment]
Ah ok --- so the "--reference" needs to be passed into sympy-next as well. Then it should take everything from a local clone.

**Comment by asmeurer** [comment]
This was fixed.
