### ISSUE TITLE
Do a shallow clone

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-bot-old#13]
We don't care about the entire history, just the HEAD.  So we should use `git clone --depth 1` (or is it `--depth 0`? I can't tell from the man page).

This applies even if we fix issue 12, because we would still be wasting time and space.

**Comment by certik** [comment]
Yes, we can do that, but the local clone takes less than 1s on my machine, so it doesn't seem to be a big deal.

**Comment by asmeurer** [comment]
Well, like I said, it saves space too.  And definitely we should do it for internet clones (because sometimes people have slow connections).  

The initial clone takes about a minute on my machine, but then takes only a second.  I don't know what it did that first time.

**Comment by certik** [comment]
Yes, for internet clones we should do that. My testing doesn't show a big improvement though (roughly 50% only).

**Comment by asmeurer** [comment]
See http://blogs.gnome.org/simos/2009/04/18/git-clones-vs-shallow-git-clones/.  I tried it with SymPy and got

``` bash

Aaron-Meurer:tmpaaronmeurer$git clone git://github.com/sympy/sympy.git sympy-deep
Cloning into sympy-deep...
remote: Counting objects: 46729, done.
remote: Compressing objects: 100% (11622/11622), done.
remote: Total 46729 (delta 36819), reused 44246 (delta 34703)
Receiving objects: 100% (46729/46729), 24.93 MiB | 793 KiB/s, done.
Resolving deltas: 100% (36819/36819), done.
Aaron-Meurer:tmpaaronmeurer$git clone --depth 1 git://github.com/sympy/sympy.git sympy-shallow
Cloning into sympy-shallow...
remote: Counting objects: 6736, done.
remote: Compressing objects: 100% (4089/4089), done.
remote: Total 6736 (delta 4199), reused 4250 (delta 2510)
Receiving objects: 100% (6736/6736), 10.02 MiB | 689 KiB/s, done.
Resolving deltas: 100% (4199/4199), done.
```

So it's a little less than half the size.  But I think this is not worth it.  I think the merge algorithm uses the history, so if we remove this, it won't be able to merge into master as well.  Therefore, I'm closing this as Won't Fix.
