### ISSUE TITLE
Master should be updated before each run

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-bot-old#140]
If you test multiple PRs, the master might be updated between runs, especially if the runs take a while.  Indeed, I just ran into a situation where the master that the PR was based against was newer than the one that SymPy bot merged into (because I was using the trick from https://groups.google.com/d/topic/sympy/UlgKewJBd_c/discussion).

**Comment by jrioux** [comment]
In my experience, even when testing multiple PRs, master is pulled before each PR, and it goes like this: First master is pulled, then the branch is pulled, thus master can be out-dated by an amount of time corresponding to the time it takes to pull the branch. You could do it the other way around, pulling the branch and then pulling master, but then the branch might be out-dated by the time it takes to pull master. Still, we might be better off with this approach, to accommodate your trick.

**Comment by asmeurer** [comment]
Here's a snippet from a multiple test run:

```
> Uploading the review to the GitHub pull request ...
>     Done.
> Check the results: https://github.com/sympy/sympy/pull/1687
> Reviewing pull request #1688
git fetch https://github.com/mrocklin/sympy triangular-predicates:test_1688
remote: Counting objects: 71, done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 63 (delta 50), reused 35 (delta 22)
Unpacking objects: 100% (63/63), done.
From https://github.com/mrocklin/sympy
 * [new branch]      triangular-predicates -> test_1688
git checkout test_1688
Switched to branch 'test_1688'
Running unit tests.
Command: git merge origin/master
Already up-to-date.
> Pull request info:
>     Author: "Matthew Rocklin" <None>
>     Repository: https://github.com/mrocklin/sympy
>     Branch: triangular-predicates
> Testing interpreter arch -i386 /Library/Frameworks/Python.framework/Versions//2.5/bin/python
Running unit tests.
Command: arch -i386 /Library/Frameworks/Python.framework/Versions//2.5/bin/python setup.py test
```

As you can see, this is a run after the first one.  If master is pulled, it's not mentioned in the log.
