### ISSUE TITLE
Add support for doctest coverage testing

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-bot-old#156]
One just needs to run `bin/coverage_doctest.py --no-colors -v` and then check the return value (the `-v` is optional, but it's probably better to put it).  This will require https://github.com/sympy/sympy/pull/1876 to work correctly.  Also, it requires that the docs be build first to work correctly.

Additionally, we should parse the summary at the end and put it in the GitHub comment.

**Comment by jrioux** [comment]
Was fixed by #161.
