### ISSUE TITLE
When an automatic merge cannot be performed, show what the conflicts are

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-bot-old#22]
Half of the time when there is a merge conflict, it is a trivial one.  Showing what the merge conflict is will make it easy to see if it's something that the author of the pull request needs to fix or if it's something that anyone can fix.

**Comment by asmeurer** [comment]
This is included in pull #31.

**Comment by certik** [comment]
This still isn't fixed --- I don't see the merge errors in the log.
