### ISSUE TITLE
review all pull requests

### ISSUE THREAD

**Issue by certik** [sympy/sympy-bot-old#3]
Allow to review more pull requests at once. And also all unreviewed pull requests.

**Comment by asmeurer** [comment]
There's now a poor-man's way of doing this by doing `./sympy-bot list-numbers | xargs -L 1 ./sympy-bot review`.  But this duplicates a lot of stuff (ideally, you could do them all at once with the same clone and without having to ask for password, etc. multiple times).  Also, this reviews _all_ open pull requests, not just unreviewed ones.

**Comment by certik** [comment]
This is already implemented. Just use `sympy-bot review 123 124 125`.
