### ISSUE TITLE
Running multiple commands and pasting just once should be possible

### ISSUE THREAD

**Issue by vperic** [sympy/sympy-bot-old#36]
In SymPy PR #625 Aaron ran tests in vanilla python, then separately for PyPy tests and doctests, then all of that again (once an error was fixed). This is a lot of spam for the pull request, especially as I envision we will have more of this as time goes on (ie. test both py2 and py3 and pypy and jython and/or whatever). 

It would be cool to be able to tell sympy-bot all the commands to run and then it'd only post once in the pull request for all the commands (but make a html report  etc. separately, of course).

**Comment by asmeurer** [comment]
sympy-next already supports running multiple tests at once, so this should not be too difficult to implement.

**Comment by certik** [comment]
I think it would help to setup google app engine application that would host all the reports (with links to github commits that were tested), so that one can easily browse it etc. So that we don't need to rely on pastehtml.com, which is unreliable (just yesterday I needed it and the site was off).

**Comment by asmeurer** [comment]
This is implemented.
