### ISSUE TITLE
web app improvements

### ISSUE THREAD

**Issue by certik** [sympy/sympy-bot-old#41]
A few suggestions:

I think that the front page should emulate this page: https://github.com/sympy/sympy/pulls, just the part about pull requests. With all the info, just do it better and more usable. So there would be buttons like "mergeable", "open", "close", "recent", "sort by contributors 'newness' to sympy" and so on. And we can make it really usable and put a big link to sympy.org for it, so that people start reviewing things more.

It would be awesome if we could have all the important metadata in the webapp, and then even a search function there, which is something that is annoyingly missing from GitHub's interface. Indeed, if it were more or less like the GitHub page (though I could think of a few improvements :-), that would be great.

It would also be cool if it were full of html 5, though I realize that that's way more work :)

Could we also add "by whomever" (i.e., the person who did the review)?
Yes, also together with the picture and put everything into a nice table. And add buttons to sort by various criteria.

**Issues that are fixed now:**

"Repository and branch: https://github.com/smichr/sympy polyx": I would make both repo and branch links (now only branch is a link).

I found another bug:

http://reviews.sympy.org/report/agZzeW1weTNyCwsSBFRhc2sYiHUM

if I upload a test result, before the app updates the list of pull requests from github, the pull request number is missing. Internally, if I can't find the pull request in the database, I should create the pull request, with the given number anyway (in the database). The update will then just update the data about it, so all will work.

fix json (use try/except)

sort the pull request by the "creation date" on the front page, and also split them to "can be merged", "can't be merged".

The pull requests currently remain on the front page forever. I'll implement hiding the closed pull requests (closed pull requests are listed at the end of the page).

On the main page I would add a title of every pull request, instead of just a number.

Implement automatic updates of issues (remove Update) button.

**Comment by certik** [comment]
Author currently is missing after the latest upgrade. Need to fix that. But otherwise most things are already fixed.

**Comment by certik** [comment]
Authors fixed.

**Comment by asmeurer** [comment]
This is too much to keep track of, so I'm going to split this all into multiple issues.

**Comment by asmeurer** [comment]
OK, I split this into a bunch of issues.  Please close any ones that were already fixed (and fix the description/title if I got it wrong).

Also, I didn't know the priority for some of them, so I left it off.
