### ISSUE TITLE
Create pull requests in the database if they aren't found

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-bot-old#52]
I found another bug:

http://reviews.sympy.org/report/agZzeW1weTNyCwsSBFRhc2sYiHUM

if I upload a test result, before the app updates the list of pull requests from github, the pull request number is missing. Internally, if I can't find the pull request in the database, I should create the pull request, with the given number anyway (in the database). The update will then just update the data about it, so all will work.

**Comment by certik** [comment]
This should be already fixed. Let me know if it still doesn't work.
