### ISSUE TITLE
Copy over py3k-sympy from reference directory

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-bot-old#58]
If the reference directory is a local git repository, it should manually copy over the py3k-sympy (which is what sympy-py3k is going to be renamed to btw) as a starting point, which will make use2to3 run way faster if it's already been done.

**Comment by asmeurer** [comment]
See https://github.com/sympy/sympy/pull/671 about renaming sympy-py3k to py3k-sympy.

**Comment by jrioux** [comment]
I guess this can be closed since #125 has been merged?

**Comment by asmeurer** [comment]
Yep. Didn't know there was an issue for it.
