### ISSUE TITLE
Better html output

### ISSUE THREAD

**Issue by certik** [sympy/sympy-bot-old#6]
The html output currently only shows the results of the documentation tests. It should show everything.

**Comment by ness01** [comment]
I think it shows everything? It's just all a bit intermingled.

**Comment by certik** [comment]
Ah, you are right:

http://pastehtml.com/view/1eddx9d.html

I misread the output. So yes, this should be disentangled somehow, and also at the top there should be some 3 big green/red signs for tests, doctests and documentation tests. So that one can quickly see if all is ok. So for example for the report above, it would be green for tests, green for doctests and red for documentation.

Hopefully we'll manage to robustly fix the failure. Are you getting it too on your computer?

**Comment by ness01** [comment]
Yes I get the same failure.

If I have time today I will try to disentangle the output.

**Comment by asmeurer** [comment]
Closing this in favor of #102.
