### ISSUE TITLE
The merge conflicts should be posted somewhere

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-bot-old#60]
Sometimes when a branch can't be merged cleanly, the conflict is just a trivial fix (like an import change), and sometimes it's not, but the point is that we don't know unless we manually try it.  So SymPy-Bot should put what the conflicts are when it can't merge cleanly so that we can see if it's something that we can just easily fix or not.

**Comment by certik** [comment]
I think it's fixed, so I am closing this one. The conflicts are posted in the log.
