### ISSUE TITLE
urllib2.HTTPError (500) kills SymPy-Bot

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-bot-old#68]
> Uploading test results
> Traceback (most recent call last):
>   File "./sympy-bot", line 244, in <module>
>     main()
>   File "./sympy-bot", line 96, in main
>     review(n, options)
>   File "./sympy-bot", line 226, in review
>     report_url = reviews_sympy_org_upload(data, url_base)
>   File "/Users/aaronmeurer/Documents/python/sympy/sympy-bot/utils.py", line 152, in reviews_sympy_org_upload
>     data["testcommand"], data["log"])
>   File "/Users/aaronmeurer/Documents/python/sympy/sympy-bot/jsonrpc.py", line 48, in **call**
>     url = urlopen(request)
>   File "/sw/lib/python2.7/urllib2.py", line 126, in urlopen
>     return _opener.open(url, data, timeout)
>   File "/sw/lib/python2.7/urllib2.py", line 400, in open
>     response = meth(req, response)
>   File "/sw/lib/python2.7/urllib2.py", line 513, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/sw/lib/python2.7/urllib2.py", line 438, in error
>     return self._call_chain(_args)
>   File "/sw/lib/python2.7/urllib2.py", line 372, in _call_chain
>     result = func(_args)
>   File "/sw/lib/python2.7/urllib2.py", line 521, in http_error_default
>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
> urllib2.HTTPError: HTTP Error 500: Internal Server Error

And then it just stopped.  It should try again.  I also had it set to test another pull request, but it did not to that either.

**Comment by certik** [comment]
Thanks for the report. I have looked up the server logs and this is the corresponding failure:

```
129.138.31.230 - - [23/Nov/2011:11:16:32 -0800] "POST /async HTTP/1.1" 500 0 - "Python-urllib/2.7" "reviews.sympy.org" ms=75516 cpu_ms=420 api_cpu_ms=0 cpm_usd=0.015717 loading_request=1 exit_code=104 instance=00c61b117c9f2734748352f45f7c8a51bf897f
E 2011-11-23 11:16:32.507
<class 'google.appengine.runtime.DeadlineExceededError'>: 
Traceback (most recent call last):
  File "/base/data/home/apps/sympy3/2.354550777508557165/main.py", line 1, in <module>
    from app.main import main
  File "/base/data/home/apps/sympy3/2.354550777508557165/app/main.py", line 15, in <module>
    from google.appengine.ext.webapp import template
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/template.py", line 68, in <module>
    import django.template
  File "/base/python_runtime/python_lib/versions/third_party/django-1.2/django/template/__init__.py", line 1052, in <module>
    add_to_builtins('django.template.defaultfilters')
  File "/base/python_runtime/python_lib/versions/third_party/django-1.2/django/template/__init__.py", line 1049, in add_to_builtins
    builtins.append(import_library(module))
  File "/base/python_runtime/python_lib/versions/third_party/django-1.2/django/template/__init__.py", line 987, in import_library
    mod = import_module(taglib_module)
  File "/base/python_runtime/python_lib/versions/third_party/django-1.2/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/base/python_runtime/python_lib/versions/third_party/django-1.2/django/template/defaultfilters.py", line 1, in <module>
    """Default variable filters."""
I 2011-11-23 11:16:32.509
This request caused a new process to be started for your application, and thus caused your application code to be loaded for the first time. This request may thus take longer and use more CPU than a typical request for your application.
W 2011-11-23 11:16:32.509
A serious problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may be throwing exceptions during the initialization of your application. (Error code 104)
```

It is the only failure of this kind, after I lowered the github updates frequency so that we don't run over quota. This error above occurs when the google app engine needs to load a new instance, and in my experience, unfortunately, such a request fails many times (it either takes too much time or something). The solution is to simply retry the request (like in 2s), and this should be implemented in the sympy-bot to simply keep retrying.
