### ISSUE TITLE
--no-upload option

### ISSUE THREAD

**Issue by PreludeAndFugue** [sympy/sympy-bot-old#8]
The default value is `True` (that is, don't upload). This is passed to the `review` function in the `upload` parameter. Note that this is `upload` not `no-upload`. Then if `upload` is `True` it will attempt to upload. But `True` initially meant don't upload.

So the meaning of this parameter is being negated.

**Comment by certik** [comment]
Yeah, I changed the meaning probably. Would you send a patch fixing it please?

**Comment by asmeurer** [comment]
I don't really see a problem here.  The command line switch needs to be no-upload, as the default is to upload.  But the upload variable in the program makes perfect sense.  I'm certainly not confused by it.
