### ISSUE TITLE
Can't use sympy-bot upon windows XP

### ISSUE THREAD

**Issue by goodok** [sympy/sympy-bot-old#85]
Can't use sympy-bot upon windows XP

**Comment by asmeurer** [comment]
What happens when you try to run it? Is it just an issue of correctly using os.path.join?

**Comment by goodok** [comment]
It is related with the lines like 'cmd ("cd %s; git clone ...")' that is when a few commands run as one line.
In windows XP the separator must be strictly "&&", not ";". I supposed that "&&" is still valid for OS X too.

I have changed this lines on my win machine, and it became workable for this machine. But I have not tested this branch in linux yet. I will test and publish it tomorrow (A tree fell on my sister's car and broke the rear window)

**Comment by asmeurer** [comment]
`&&` is not only valid in UNIX, but it is better, as it will prevent execution of the second command if the first fails.

**Comment by goodok** [comment]
See pull request:
https://github.com/sympy/sympy-bot/pull/86

**Comment by vramana** [comment]
@asmeurer I think you can close this issue as you have closed #86
