### ISSUE TITLE
Move away from pastehtml

### ISSUE THREAD

**Issue by certik** [sympy/sympy-bot-old#9]
pastehtml has bugs, and in this pull request:

https://github.com/sympy/sympy/pull/253

pastehtml decided to serve spam instead of our report. So that's the last bit. We should create a simple service for this on the google app engine, to host the reports.

**Comment by certik** [comment]
And here it serves a different page instead:

https://github.com/sympy/sympy/pull/288

**Comment by asmeurer** [comment]
How hard is this going to be to set up?  Pastehtml has done it again at https://github.com/sympy/sympy/pull/299.

**Comment by certik** [comment]
It shouldn't be very hard, at least to get started. I would estimate roughly 3 hours of work total. One needs to write the app, set it up at the app engine, and preferably create some subdomain for it at .sympy.org. Which address should we use it for? review.sympy.org, or reviews.sympy.org?

**Comment by certik** [comment]
Some time ago, I wrote this:

http://repos.sympy.org/

it's unrelated, but it shows that you can create nice web interface to github quite easily on the app engine.

**Comment by asmeurer** [comment]
Another idea: we could create some dummy git repository, say, "sympy-bot reviews," and give everyone push access to it.  Then, make sympy-bot push up the html page to gh-pages.

**Comment by asmeurer** [comment]
This was done.
